apiVersion: v1
kind: ReplicationController
metadata:
  name: web-v1
  labels:
    app: web
    version: v1
spec:
  replicas: 2
  selector:
    app: web
    version: v1
  template:
    metadata:
      labels:
        app: web
        version: v1
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
