apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc-v2
spec:
  replicas: 3
  selector:
    app: myapp
    version: v2
  template:
    metadata:
      labels:
        app: myapp
        version: v2
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:0.2.3
        # listen on 8080 so it matches your NodePort service's targetPort
        args:
          - "-listen=:8080"
          - "-text=Hello from v2"
        ports:
        - containerPort: 8080
