apiVersion: v1
kind: ReplicationController
metadata:
  name: web-v2
  labels:
    app: web
    version: v2
spec:
  replicas: 2
  selector:
    app: web
    version: v2
  template:
    metadata:
      labels:
        app: web
        version: v2
    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - containerPort: 80
