apiVersion: v1
kind: ReplicationController
metadata:
  name: web-rc
  labels:
    app: web
spec:
  replicas: 3
  selector:
    app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
