apiVersion: v1
kind: Service
metadata:
  name: web-nodeport
spec:
  type: NodePort
  selector:
    app: web   # this matches BOTH v1 and v2 pods
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080   # fixed port on the nodes; change if you prefer
